[package]
name = "test-ignore-if"
version = "0.1.0"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.9"
lazy_static = "1.3"
proc-macro2 = "0.4"
regex = "1.1"
quote= "0.6"
syn ="0.15"
